### ISSUE TITLE
Цитируем Роберта Мартина 

### ISSUE THREAD

**Issue by Vasliska1** [belovlaska/itmo#13]
https://github.com/belovlaska/itmo/blob/d39e88d40c8f66be0fb5a257f2f0ee80b90e19f0/Programming/lab6_prog_v2/client/src/main/java/client/network/TCPClient.java#L42

**Comment by Vasliska1** [comment]
Есть такая книжка "Чистый код" Роберта Мартина, советую почитать
так вот, он там писал:
"Компактность!
Первое правило: функции должны быть компактными. Второе правило: функции должны быть еще компактнее.
Желательно, чтобы длина функции не превышала 20 строк.

функции не должны иметь отступов более чем на два уровня. -- то есть вложенности должно быть максимально 2"

слишком тяжело этот метод читается, надо попробовать разбить

**Comment by Vasliska1** [comment]
С сервером тоже самое, надо TCPServer делить на зоны ответственности

**Comment by belovlaska** [comment]
fixed
